include: package:flutter_lints/flutter.yaml
language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
errors:
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    always_declare_return_types: error
    annotate_overrides: warning
    avoid_bool_literals_in_conditional_expressions: info
    avoid_catching_errors: error
    avoid_double_and_int_checks: error
    avoid_empty_else: error
    avoid_escaping_inner_quotes: info
    avoid_final_parameters: info
    avoid_function_literals_in_foreach_calls: warning
    avoid_implementing_value_types: error
    avoid_init_to_null: info
    avoid_js_rounded_ints: error
    avoid_multiple_declarations_per_line: info
    avoid_null_checks_in_equality_operators: info
    avoid_positional_boolean_parameters: warning
    avoid_private_typedef_functions: info
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: warning
    avoid_return_types_on_setters: info
    avoid_returning_null_for_void: info
    avoid_returning_this: info
    avoid_setters_without_getters: info
    avoid_shadowing_type_parameters: error
    avoid_single_cascade_in_expression_statements: info
    avoid_slow_async_io: info
    avoid_type_to_string: error
    avoid_types_as_parameter_names: error
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    avoid_void_async: info
    avoid_web_libraries_in_flutter: error
    await_only_futures: warning
    camel_case_extensions: info
    camel_case_types: info
    cancel_subscriptions: error
    cascade_invocations: info
    cast_nullable_to_non_nullable: error
    close_sinks: error
    collection_methods_unrelated_type: warning
    combinators_ordering: info
    comment_references: error
    conditional_uri_does_not_exist: error
    constant_identifier_names: info
    control_flow_in_finally: error
    curly_braces_in_flow_control_structures: warning
    dangling_library_doc_comments: warning
    depend_on_referenced_packages: error
    deprecated_consistency: warning
    deprecated_member_use_from_same_package: warning
    directives_ordering: info
    empty_catches: error
    empty_constructor_bodies: info
    empty_statements: error
    exhaustive_cases: error
    file_names: warning
    hash_and_equals: error
    implementation_imports: warning
    implicit_call_tearoffs: info
    implicit_reopen: error
    invalid_case_patterns: error
    iterable_contains_unrelated_type: warning
    join_return_with_assignment: info
    leading_newlines_in_multiline_strings: info
    library_annotations: warning
    library_names: error
    library_prefixes: info
    library_private_types_in_public_api: error
    list_remove_unrelated_type: warning
    literal_only_boolean_expressions: error
    matching_super_parameters: info
    missing_whitespace_between_adjacent_strings: info
    no_adjacent_strings_in_list: info
    no_duplicate_case_values: error
    no_leading_underscores_for_library_prefixes: info
    no_leading_underscores_for_local_identifiers: info
    no_literal_bool_comparisons: info
    no_logic_in_create_state: error
    no_runtimeType_toString: error
    no_self_assignments: error
    no_wildcard_variable_uses: warning
    non_constant_identifier_names: info
    noop_primitive_operations: warning
    null_check_on_nullable_type_parameter: error
    null_closures: error
    only_throw_errors: error
    overridden_fields: error
    package_names: error
    package_prefixed_library_names: info
    parameter_assignments: error
    prefer_adjacent_string_concatenation: info
    prefer_asserts_in_initializer_lists: info
    prefer_asserts_with_message: warning
    prefer_collection_literals: info
    prefer_conditional_assignment: info
    prefer_const_constructors: info
    prefer_const_constructors_in_immutables: info
    prefer_const_declarations: info
    prefer_const_literals_to_create_immutables: info
    prefer_constructors_over_static_methods: info
    prefer_contains: info
    prefer_double_quotes: info
    prefer_final_fields: info
    prefer_final_in_for_each: info
    prefer_final_locals: info
    prefer_for_elements_to_map_fromIterable: info
    prefer_function_declarations_over_variables: info
    prefer_generic_function_type_aliases: info
    prefer_if_elements_to_conditional_expressions: info
    prefer_if_null_operators: info
    prefer_initializing_formals: info
    prefer_inlined_adds: info
    prefer_interpolation_to_compose_strings: info
    prefer_is_empty: info
    prefer_is_not_empty: info
    prefer_is_not_operator: info
    prefer_iterable_whereType: info
    prefer_mixin: warning
    prefer_null_aware_method_calls: info
    prefer_null_aware_operators: info
    prefer_spread_collections: info
    prefer_typing_uninitialized_variables: error
    prefer_void_to_null: warning
    provide_deprecation_message: info
    recursive_getters: error
    require_trailing_commas: info
    secure_pubspec_urls: warning
    sized_box_for_whitespace: info
    sized_box_shrink_expand: info
    slash_for_doc_comments: info
    sort_child_properties_last: info
    sort_constructors_first: info
    sort_pub_dependencies: info
    sort_unnamed_constructors_first: info
    test_types_in_equals: error
    throw_in_finally: error
    tighten_type_of_initializing_formals: info
    type_annotate_public_apis: error
    type_init_formals: info
    type_literal_in_constant_pattern: error
    unawaited_futures: error
    unnecessary_await_in_return: info
    unnecessary_brace_in_string_interps: info
    unnecessary_breaks: info
    unnecessary_const: info
    unnecessary_constructor_name: info
    unnecessary_getters_setters: info
    unnecessary_lambdas: info
    unnecessary_late: info
    unnecessary_new: info
    unnecessary_null_aware_assignments: info
    unnecessary_null_aware_operator_on_extension_on_nullable: info
    unnecessary_null_checks: info
    unnecessary_null_in_if_null_operators: info
    unnecessary_nullable_for_final_variable_declarations: info
    unnecessary_overrides: info
    unnecessary_raw_strings: info
    unnecessary_statements: warning
    unnecessary_string_escapes: info
    unnecessary_string_interpolations: info
    unnecessary_this: info
    unnecessary_to_list_in_spreads: info
    unrelated_type_equality_checks: warning
    unsafe_html: warning
    use_build_context_synchronously: error
    use_colored_box: info
    use_decorated_box: info
    use_enums: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: info
    use_is_even_rather_than_modulo: info
    use_key_in_widget_constructors: warning
    use_late_for_private_fields_and_variables: info
    use_named_constants: info
    use_raw_strings: info
    use_rethrow_when_possible: error
    use_setters_to_change_properties: info
    use_string_buffers: warning
    use_string_in_part_of_directives: error
    use_super_parameters: info
    use_test_throws_matchers: info
    valid_regexps: error
    void_checks: error
linter:
  rules:
    - prefer_single_quotes
    - always_declare_return_types
    - cascade_invocations
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_returning_this
    - cancel_subscriptions
    - deprecated_consistency
    - deprecated_member_use_from_same_package
    - invalid_case_patterns
    - join_return_with_assignment
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_escaping_inner_quotes
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
    - avoid_private_typedef_functions
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - close_sinks
    - collection_methods_unrelated_type
    - combinators_ordering
    - comment_references
    - conditional_uri_does_not_exist
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    - dangling_library_doc_comments
    - depend_on_referenced_packages
    - empty_constructor_bodies
    - empty_statements
    - exhaustive_cases
    - file_names
    - hash_and_equals
    - implementation_imports
    - implicit_call_tearoffs
    - implicit_reopen
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - matching_super_parameters
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - no_literal_bool_comparisons
    - no_logic_in_create_state
    - no_runtimeType_toString
    - no_self_assignments
    - no_wildcard_variable_uses
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - only_throw_errors
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - recursive_getters
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_init_formals
    - type_literal_in_constant_pattern
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_colored_box
    - use_decorated_box
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_string_in_part_of_directives
    - use_super_parameters
    - use_test_throws_matchers
    - valid_regexps
    - void_checks

analyzer:
  exclude:
    - lib/generated/**